(function(){
"use strict";
const study=window.URIS_VOCABULARY||[],candidates=window.URIS_CANDIDATE_WORDS||[],terms=window.URIS_TERMS||[],setMembers=window.URIS_VOCABULARY_SETS||{};
const termByWord=new Map(terms.map(x=>[x.word,x])),studyByWord=new Map(study.map(x=>[x.word,x]));
const fmt=v=>new Intl.NumberFormat("en-US").format(v),esc=v=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
document.querySelectorAll("[data-year]").forEach(n=>n.textContent=new Date().getFullYear());
const navToggle=document.querySelector(".nav-toggle"),nav=document.querySelector(".site-nav");
if(navToggle&&nav)navToggle.addEventListener("click",()=>{const open=nav.classList.toggle("is-open");navToggle.setAttribute("aria-expanded",String(open));});

const body=document.querySelector("#vocabulary-body");
if(body){
 const search=document.querySelector("#vocabulary-search"),pos=document.querySelector("#pos-filter"),affix=document.querySelector("#affix-filter"),affixControl=document.querySelector("#affix-control"),sort=document.querySelector("#sort-select"),count=document.querySelector("#result-count"),clear=document.querySelector("#clear-filters"),head=document.querySelector("#vocabulary-head"),description=document.querySelector("#set-description"),note=document.querySelector("#results-note"),tabs=[...document.querySelectorAll("[data-vocabulary-set]")],studyWords=new Set(study.map(x=>x.word));
 let active="candidate";
 const records=set=>set==="study"?study:set==="candidate"?candidates.map(x=>({...termByWord.get(x.word),...x})):(setMembers[set]||[]).map(w=>termByWord.get(w)).filter(Boolean);
 const affixes=item=>active==="study"?(item.affixes||[]):active==="candidate"?[item.prefix,item.suffix].filter(Boolean):[];
 function fillPos(){const values=[...new Set(records(active).map(x=>x.pos).filter(x=>x&&x!=="Pending verification"))].sort();pos.innerHTML='<option value="">All parts of speech</option>'+values.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");}
 function fillAffixes(){const values=records(active).flatMap(affixes);affix.innerHTML='<option value="">All recorded affixes</option>'+[...new Set(values)].sort().map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");}
 function fillSort(){sort.innerHTML=active==="study"?'<option value="word:asc">Word A to Z</option><option value="frequency:desc">Highest frequency</option><option value="usefulness:desc">Highest usefulness</option><option value="difficulty:desc">Highest difficulty</option>':'<option value="word:asc">Word A to Z</option><option value="word:desc">Word Z to A</option>';}
 function updateUI(){
  tabs.forEach(tab=>{const selected=tab.dataset.vocabularySet===active;tab.classList.toggle("is-active",selected);tab.setAttribute("aria-selected",String(selected));tab.tabIndex=selected?0:-1;});
  affixControl.hidden=!["candidate","study"].includes(active);
  const copy={candidate:'<strong>Candidate Pool · 138 words.</strong> The formal medical and STEM pool taken forward for expert ratings after cross-referencing the HKUST STEM and COCA academic resources.',study:'<strong>Current Study Set · 34 words.</strong> The target words implemented in the digital-flashcard study, with verified lexical variables and expert ratings.',life:'<strong>HKUST Life Science · 433 words.</strong> The Life Science discipline list recorded in the HKUST STEM Vocabulary source used by the project.',medical:'<strong>HKUST × COCA Medicine · 468 words.</strong> Words found in both project source lists and labelled Medicine in the recorded COCA domain field.'};
  const notes={candidate:'Affixes reproduce the project workbook coding. Unverified Chinese terms are clearly marked.',study:'Traditional Chinese meanings come from the implemented URIS study materials. Ratings use 7-point scales.',life:'POS uses the project COCA source where available. Chinese terms use official Hong Kong Education Bureau science glossaries where matched.',medical:'POS uses the project COCA source. Chinese terms use official Hong Kong Education Bureau science glossaries where matched.'};
  description.innerHTML=copy[active];note.textContent=notes[active];
  head.innerHTML=active==="study"?'<tr><th>Word</th><th>POS</th><th>繁體中文</th><th>iWeb frequency</th><th>Affix</th><th>Usefulness</th><th>Difficulty</th></tr>':active==="candidate"?'<tr><th>Word</th><th>POS</th><th>繁體中文</th><th>Recorded affix</th><th>Research stage</th></tr>':'<tr><th>Word</th><th>POS</th><th>繁體中文</th><th>Vocabulary source</th></tr>';
  search.value="";pos.value="";fillPos();fillAffixes();fillSort();
 }
 const zhCell=item=>`<span class="zh-term${item.zh==="待核實"?" is-pending":""}">${esc(item.zh||"待核實")}</span><span class="item-id">${esc(item.zhSource||"Pending verification")}</span>`;
 function render(){
  const query=search.value.trim().toLowerCase(),source=records(active);let result=source.filter(item=>{const a=affixes(item),hay=`${item.word} ${item.pos||""} ${item.zh||""} ${a.join(" ")}`.toLowerCase();return(!query||hay.includes(query))&&(!pos.value||item.pos===pos.value)&&(!affix.value||a.includes(affix.value));});
  const[key,direction]=sort.value.split(":");result=result.slice().sort((a,b)=>{const l=a[key]??"",r=b[key]??"",cmp=typeof l==="string"?l.localeCompare(r):l-r;return direction==="desc"?-cmp:cmp;});count.textContent=`${result.length} of ${source.length} words`;
  if(!result.length){body.innerHTML='<tr><td colspan="7" class="empty-state">No words match these filters.</td></tr>';return;}
  if(active==="study")body.innerHTML=result.map(x=>`<tr><th scope="row" data-label="Word"><span class="word-name">${esc(x.word)}</span><span class="item-id">${x.id}</span></th><td data-label="POS">${esc(x.pos)}</td><td data-label="繁體中文">${zhCell(x)}</td><td data-label="iWeb frequency" class="number">${fmt(x.frequency)}</td><td data-label="Affix">${x.affixes.length?x.affixes.map(v=>`<span class="tag">${esc(v)}</span>`).join(" "):'<span class="muted">Not coded</span>'}</td><td data-label="Usefulness" class="number">${x.usefulness.toFixed(2)}<span class="scale"> / 7</span></td><td data-label="Difficulty" class="number">${x.difficulty.toFixed(2)}<span class="scale"> / 7</span></td></tr>`).join("");
  else if(active==="candidate")body.innerHTML=result.map(x=>`<tr><th scope="row" data-label="Word"><span class="word-name">${esc(x.word)}</span></th><td data-label="POS">${esc(x.pos)}</td><td data-label="繁體中文">${zhCell(x)}</td><td data-label="Recorded affix">${affixes(x).length?affixes(x).map(v=>`<span class="tag">${esc(v)}</span>`).join(" "):'<span class="muted">Not recorded</span>'}</td><td data-label="Research stage"><span class="status">${studyWords.has(x.word)?"Current study subset":"Expert-rating candidate"}</span></td></tr>`).join("");
  else{const label=active==="life"?"HKUST Life Science":"HKUST × COCA Medicine";body.innerHTML=result.map(x=>`<tr><th scope="row" data-label="Word"><span class="word-name">${esc(x.word)}</span></th><td data-label="POS">${esc(x.pos)}</td><td data-label="繁體中文">${zhCell(x)}</td><td data-label="Vocabulary source">${label}</td></tr>`).join("");}
 }
 [search,pos,affix,sort].forEach(c=>c.addEventListener(c===search?"input":"change",render));clear.addEventListener("click",()=>{search.value="";pos.value="";affix.value="";sort.value="word:asc";render();search.focus();});tabs.forEach(tab=>tab.addEventListener("click",()=>{active=tab.dataset.vocabularySet;updateUI();render();}));
 const params=new URLSearchParams(location.search);if(["candidate","study","life","medical"].includes(params.get("set")))active=params.get("set");updateUI();if(params.has("search"))search.value=params.get("search");render();
}

const affixList=document.querySelector("#affix-list");
if(affixList){
 const details=document.querySelector("#affix-details"),search=document.querySelector("#affix-search"),type=document.querySelector("#affix-type-filter"),map=new Map();study.forEach(item=>item.affixes.forEach(value=>{if(!map.has(value))map.set(value,[]);map.get(value).push(item);}));
 const entries=[...map.entries()].map(([value,items])=>({value,items,background:candidates.filter(x=>!studyByWord.has(x.word)&&[x.prefix,x.suffix].includes(value)).slice(0,4),type:value.endsWith("-")?"prefix":"suffix"})).sort((a,b)=>a.value.localeCompare(b.value));let selected=entries[0]?.value;
 function show(entry){if(!entry){details.innerHTML='<p class="muted">Select an affix to view associated words.</p>';return;}details.innerHTML=`<p class="eyebrow">${entry.type}</p><h2>${esc(entry.value)}</h2><h3>Current study words</h3><ul class="word-lines">${entry.items.map(x=>`<li><a href="vocabulary.html?set=study&amp;search=${encodeURIComponent(entry.value)}">${esc(x.word)}</a><span>${esc(x.pos)}</span></li>`).join("")}</ul>${entry.background.length?`<h3 class="background-heading">Background-recorded examples</h3><p class="compact-note">Selected examples from the 138-word candidate pool. They are not part of the 34-word core set.</p><ul class="word-lines secondary-lines">${entry.background.map(x=>`<li><a href="vocabulary.html?set=candidate&amp;search=${encodeURIComponent(x.word)}">${esc(x.word)}</a><span>Candidate pool</span></li>`).join("")}</ul>`:""}`;}
 function render(){const query=search.value.trim().toLowerCase(),filtered=entries.filter(e=>(!query||e.value.toLowerCase().includes(query)||e.items.some(x=>x.word.includes(query))||e.background.some(x=>x.word.includes(query)))&&(!type.value||e.type===type.value));if(!filtered.some(e=>e.value===selected))selected=filtered[0]?.value;affixList.innerHTML=filtered.length?filtered.map(e=>`<button class="affix-card${e.value===selected?" is-active":""}" data-affix="${esc(e.value)}"><span>${esc(e.value)}</span><small>${e.type} · ${e.items.length} core ${e.items.length===1?"word":"words"}</small></button>`).join(""):'<p class="empty-state">No affixes match these filters.</p>';affixList.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{selected=b.dataset.affix;render();}));show(entries.find(e=>e.value===selected));}
 [search,type].forEach(c=>c.addEventListener(c===search?"input":"change",render));render();
}
})();
